plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'bananaforscale.com.timechange'
    compileSdk 35

    defaultConfig {
        applicationId "bananaforscale.com.timechange"
        minSdk 30
        targetSdk 35
        versionCode 11
        versionName "1.2"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/atomicfu.kotlin_module']
        }
    }

    compileOptions {
        sourceCompatibility = 17
        targetCompatibility = 17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation libs.androidx.core.ktx

    // Kotlin components
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation libs.androidx.activity.ktx

    // Lifecycle components
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx

    // Material components
    implementation libs.android.material

    // Wear libraries
    implementation libs.androidx.wear

    // Watch face specific libraries
    implementation libs.wear.watchface.complications.data
    implementation libs.wear.watchface.complications.data.source

    implementation libs.wear.watchface
    implementation libs.wear.watchface.client
    implementation libs.wear.watchface.complications.rendering
    implementation libs.wear.watchface.data
    implementation libs.wear.watchface.editor
    implementation libs.wear.watchface.style
}
