plugins {
    id 'com.android.application'
}

android {
    namespace 'bananaforscale.com.timechange.wff'
    compileSdk 34

    defaultConfig {
        applicationId "bananaforscale.com.timechange.wff"
        minSdk 34
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}
